version: "3.3"

services:
  nginx:
    depends_on:
      - client
      - api
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
    networks:
      - api-networks
  api:
    container_name: api
    build: ./Chat_BE
    ports:
      - 1337:1337
    restart: always
    env_file:
      - ./Chat_BE/.env
    networks:
      - api-networks
  client:
    container_name: client
    build: ./Chat_FE_React
    volumes:
      - /Chat_FE_React:/app/node_modules
    # ports:
    #   - 3000:3000
    restart: always
    depends_on:
      - api
    env_file:
      - ./Chat_FE_React/.env
    networks:
      - api-networks

networks:
  api-networks:
    driver: bridge
