version: "3.3"

services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - backend
      - frontend
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - 80:80
  backend:
    image: backend
    container_name: backend
    build: ../Chat_BE
    volumes:
      - ../Chat_BE:/usr/src/app
    ports:
      - 1337:1337
    restart: on-failure
    env_file:
      - ../Chat_BE/.env
  frontend:
    image: frontend
    container_name: frontend
    build: ../Chat_FE_React
    volumes:
      - /Chat_FE_React:/app/node_modules
    ports:
      - 3001:3001
    restart: on-failure
    env_file:
      - ../Chat_FE_React/.env
